name: build test publish
on:
  push:
    branches:
      - release*
      - master
      - main
jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '***SKIPBUILD***')"
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.9']
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Config github user
        run: |
          git config --global user.email "idm_bamboo_user@idmod.org"
          git config --global user.name "BambooUser-IDM"
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - id: build-install
        name: Build and install package
        uses: ./.github/actions/build-install-package
        with:
          package_file: 'setup.py'
      - name: run tests
        run: python -m unittest discover .
        working-directory: ./tests
      - name: cache camps staging login
        run: |
          python .dev_scripts/create_auth_token_args.py -c https://comps2.idmod.org -u ${{ secrets.COMPS_USER }} -p ${{ secrets.COMPS_PASSWORD }}
        working-directory: ./
      - name: run workflow tests
        run: python test_sim.py
        working-directory: ./tests/sim_tests
      - name: cache camps login
        run: |
          python .dev_scripts/create_auth_token_args.py -c https://comps.idmod.org -u ${{ secrets.COMPS_USER }} -p ${{ secrets.COMPS_PASSWORD }}
        working-directory: ./
      - name: run examples with Eradication from pip install using snakemake
        run: |
          pip install snakemake
          pip install pulp==2.7.0
          snakemake --cores all
        working-directory: ./examples
      - name: Push version bump
        run: git push
      - name: twine upload
        run: twine upload --verbose --repository-url https://packages.idmod.org/api/pypi/idm-pypi-staging/ --username ${{ secrets.ARTIFACTORY_USER }} --password ${{ secrets.ARTIFACTORY_TOKEN }} ${{ steps.build-install.outputs.wheel-file }}
      - name: Add wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: emodpy-hiv.wheel
          path: ${{ steps.build-install.outputs.wheel-file }}

