name: build test
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches-ignore:
      - 'main'

jobs:
  build_test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '***SKIPBUILD***')"
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.9 ]
    steps:
      - name: Checkout sources with LFS
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Config github user
        run: |
          git config --global user.email "idm_bamboo_user@idmod.org"
          git config --global user.name "BambooUser-IDM"
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Build and install package
        uses: ./.github/actions/build-install-package
        with:
          pyproject_file: 'pyproject.toml'
      - name: install test packages
        run: |
          python -m pip install --upgrade -r requirements.txt 
        working-directory: ./tests
      - name: run unit, sim, and country tests
        run: |
          pytest unittests/test_emod_hiv_package.py
          pytest --dist loadfile -v -m unit --junitxml="test_results_unit.xml"
          pytest --dist loadfile -v -m container --junitxml="test_results_container.xml"
        working-directory: ./tests
      - name: run examples with Eradication from pip install snakemake
        run: |
          pip install snakemake
          pip install pulp==2.7.0
          snakemake --cores all
        working-directory: ./examples
