# This workflow will rebuild emodpy-hiv Docs triggered when changes to rst, python, or requirements.txt files occur.

name: Rebuild hiv Docs
on:
  push:
    paths: 
      - '**.py'
      - '**/*docs/**'

  pull_request:
    branches:
      - '*'  

jobs:
  emodpy-hiv-Docs-Preview:

    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }} 

    # Environment Setup
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
          python-version: 3.9

    - name: Install the emodpy-hiv package
      run: |
        python -m pip install --upgrade pip
        pip install -e . --extra-index-url=https://packages.idmod.org/api/pypi/pypi-production/simple

    - name: Install documentation build requirements
      run: |
        pip install -r docs/requirements.txt --extra-index-url=https://packages.idmod.org/api/pypi/pypi-production/simple

    - name: Build docs - html - no break
      id: build-docs
      working-directory: 'docs'
      run: |
        make clean
        make htmlnobreak
        
